---
version: '3.7'
volumes:
  krb5kdc-data:

services:
  kdc:
    image: krb5-kdc:latest
    container_name: krb5-kdc
    restart: always
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    environment:
      KRB5_REALM: EXAMPLE.ORG
      KRB5_KDC: localhost
      KRB5_PASS: admin
    volumes:
      - krb5kdc-data:/var/lib/krb5kdc

  remctld:
    image: remctld:latest
    container_name: remctld
    ports:
      - "4373:4373"
    volumes:
      - ./remctld.keytab:/config/krb5.keytab:ro
      - ./conf.d:/config/conf.d:ro
      - ./scripts:/scripts:ro
