---
version: '2'
volumes:
  krb5kdc-data:

services:
  kdc:
    image: gcavalcante8808/krb5-server
    container_name: krb5-kdc
    restart: always
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    environment:
      KRB5_REALM: EXAMPLE.ORG
      KRB5_KDC: localhost
      KRB5_PASS: admin
    volumes:
      - krb5kdc-data:/var/lib/krb5kdc

  remctld:
    image: ubuntu:latest
    container_name: remctld
    ports:
      - "4373:4373"
    volumes:

